services:
  app:
    build: .
    container_name: raggae
    volumes:
      - /home/heiner/software/raggae:/app  # Map your local folder to the container
    ports:
      - "8000:8000"  # Map container's port 8000 to localhost:8000
    stdin_open: true
    tty: true
    depends_on:
      - redis
#      - chroma

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"

#  chroma:
#    image: chromadb/chromadb:latest
#    container_name: chroma
#    ports:
#      - "8001:8001"


volumes:
  app_data:
    driver: local
